app = "strapi-epf"
primary_region = "gru"

[env]
NODE_ENV = "production"
PORT = "1337"
HOST = "0.0.0.0"

[[services]]
internal_port = 1337
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[vm]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
